---
receptor_user: receptor
receptor_group: receptor

receptor_config_dir: '/etc/receptor'
receptor_socket_dir: '/var/run/receptor'
receptor_control_filename: 'receptor.sock'

receptor_tls: false
receptor_mintls13: false

receptor_tls_dir: '/etc/receptor/tls'
receptor_tls_ca_dir: '{{ receptor_tls_dir }}/ca'
receptor_tls_certfile: "{{ receptor_tls_dir }}/{{ receptor_host_identifier }}.crt"
receptor_tls_keyfile: "{{ receptor_tls_dir }}/{{ receptor_host_identifier }}.key"
receptor_ca_certfile: "{{ receptor_tls_ca_dir }}/mesh-CA.crt"
receptor_ca_keyfile: "{{ receptor_tls_ca_dir }}/mesh-CA.key"
receptor_replace_tls: false

receptor_worksign_key_dir: "/etc/receptor"
receptor_worksign_private_keyfile: "{{ receptor_worksign_key_dir }}/work_private_key.pem"
receptor_worksign_public_keyfile: "{{ receptor_worksign_key_dir }}/work_public_key.pem"

receptor_fd_limit_soft: 4096
receptor_fd_limit_hard: 8192

receptor_listener: true
receptor_local_only: false

receptor_protocol: 'tcp'
receptor_port: 27199
receptor_sign: false
receptor_verify: false

receptor_log_level: 'info'

_hostname: "{{ routable_hostname | default(ansible_host) }}"
receptor_host_identifier: "{{ (_hostname == 'localhost') | ternary('localhost.localdomain', _hostname) }}"

receptor_install_method: release # options: release, package, local, container
receptor_local_bin_file: ''
receptor_install_dir: '/usr/bin'

receptor_github_owner: ansible
receptor_github_repo: receptor

receptor_log_dir: /var/log/receptor

receptor_service_name: receptor

arch_mapping:
  armv6l: armhf
  armv7l: armhf
  aarch64: arm64
  x86_64: amd64
  i386: i386

additional_system_packages: []

additional_python_packages: []

system_pip_package: python3-pip

pip_executable: pip3
python_executable: python3

minimum_python_version: 3.9

receptor_packages: []

# Todo: Replace with non-dev ee image once available
receptor_image_name: quay.io/haoliu/awx-ee
receptor_image_tag: podman-remote
receptor_image_authfile: ''
awx_isolation_base_path: /tmp
